"""Fail closed unless frozen demo fixtures are bilingual and Google-only."""

from __future__ import annotations

import argparse
import hashlib
import json
import wave
from pathlib import Path
from typing import Any

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
MANIFEST_PATH = ROOT / "fixtures" / "demo" / "manifest.json"
REQUIRED_LANGUAGES = {"en-KE", "sw-KE"}
REQUIRED_PROJECT_ID = "agent-platform-503913"
ALLOWED_PROVIDERS = {
    "google_vertex_ai",
    "google_cloud_text_to_speech",
}


def _fail(message: str) -> None:
    raise ValueError(message)


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _inside_root(relative_path: str, label: str) -> Path:
    candidate = Path(relative_path)
    if candidate.is_absolute():
        _fail(f"{label} path must be repository-relative")
    resolved = (ROOT / candidate).resolve()
    try:
        resolved.relative_to(ROOT.resolve())
    except ValueError:
        _fail(f"{label} path escapes the repository")
    return resolved


def _validate_common(item: dict[str, Any], kind: str) -> Path:
    path = _inside_root(item["path"], f"{item.get('id', kind)} fixture")
    if not path.is_file():
        _fail(f"{kind} fixture missing: {item['path']}")
    payload = path.read_bytes()
    if len(payload) != item["bytes"]:
        _fail(f"{item['id']} byte count mismatch")
    if _sha256(path) != item["sha256"]:
        _fail(f"{item['id']} SHA-256 mismatch")
    provider = item.get("source", {}).get("provider")
    if provider not in ALLOWED_PROVIDERS:
        _fail(f"{item['id']} uses disallowed provider: {provider!r}")
    if item.get("synthetic") is not True:
        _fail(f"{item['id']} must explicitly declare synthetic=true")
    source = item.get("source", {})
    if source.get("project_id") != REQUIRED_PROJECT_ID:
        _fail(f"{item['id']} was not generated in the approved GCP project")
    if source.get("synthetic") is not True or not source.get("generated_utc"):
        _fail(f"{item['id']} requires synthetic source provenance and generation time")
    return path


def _validate_ledger(item: dict[str, Any]) -> None:
    path = _validate_common(item, "ledger")
    with Image.open(path) as image:
        if image.format != "PNG":
            _fail(f"{item['id']} must be a PNG")
        if (image.width, image.height) != (item["width"], item["height"]):
            _fail(f"{item['id']} dimensions mismatch")
    source = item["source"]
    if source["provider"] != "google_vertex_ai":
        _fail(f"{item['id']} ledger must be generated by Vertex AI")
    if source.get("model") != "gemini-3.1-flash-image" or source.get("location") != "global":
        _fail(f"{item['id']} does not use the approved Gemini image contract")
    if not str(source.get("response_mime_type", "")).startswith("image/"):
        _fail(f"{item['id']} is missing the Vertex response MIME type")
    if not isinstance(source.get("usage"), dict):
        _fail(f"{item['id']} is missing model usage provenance")
    prompt_path = _inside_root(source["prompt_path"], f"{item['id']} prompt")
    if not prompt_path.is_file() or _sha256(prompt_path) != source["prompt_sha256"]:
        _fail(f"{item['id']} prompt integrity mismatch")
    truth = item.get("ground_truth", {})
    rows = truth.get("rows", [])
    if truth.get("recorded_rows") != 2 or truth.get("gated_rows") != 1 or len(rows) != 3:
        _fail(f"{item['id']} must preserve two-record/one-gate truth")
    gated = [row for row in rows if row.get("expected_action") == "gate"]
    if len(gated) != 1 or gated[0].get("amount_ksh") is not None:
        _fail(f"{item['id']} unreadable amount must remain null and gated")


def _validate_voice(item: dict[str, Any]) -> None:
    path = _validate_common(item, "voice")
    if not item.get("transcript") or not item.get("english_translation"):
        _fail(f"{item['id']} requires transcript and English translation")
    with wave.open(str(path), "rb") as audio:
        duration = audio.getnframes() / audio.getframerate()
    if abs(duration - item["duration_seconds"]) > 0.02:
        _fail(f"{item['id']} duration mismatch")
    source = item["source"]
    if source["provider"] != "google_cloud_text_to_speech":
        _fail(f"{item['id']} voice must be generated by Google Cloud Text-to-Speech")
    if source.get("model") != "gemini-2.5-flash-tts" or source.get("location") != "eu":
        _fail(f"{item['id']} does not use the approved Gemini TTS contract")
    if source.get("speaker") != "Kore":
        _fail(f"{item['id']} is missing the approved Google TTS speaker")
    if source.get("transcript_sha256") != hashlib.sha256(
        item["transcript"].encode("utf-8")
    ).hexdigest():
        _fail(f"{item['id']} transcript integrity mismatch")
    style_prompt = source.get("style_prompt", "")
    if not style_prompt or source.get("style_prompt_sha256") != hashlib.sha256(
        style_prompt.encode("utf-8")
    ).hexdigest():
        _fail(f"{item['id']} style prompt integrity mismatch")


def verify(manifest_path: Path = MANIFEST_PATH, *, allow_pending: bool = False) -> dict[str, Any]:
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if manifest.get("schema_version") != 2:
        _fail("fixture manifest schema_version must be 2")
    if manifest.get("synthetic_only") is not True:
        _fail("fixture manifest must declare synthetic_only=true")
    provider_policy = manifest.get("provider_policy", {})
    if provider_policy.get("generated_media") != "google_only":
        _fail("fixture manifest must declare generated_media=google_only")
    if set(provider_policy.get("allowed", [])) != ALLOWED_PROVIDERS:
        _fail("fixture manifest provider allowlist must contain only approved Google surfaces")
    ledgers = manifest.get("ledgers", [])
    voices = manifest.get("voices", [])
    if manifest.get("release_ready") is not True:
        if not allow_pending:
            _fail("fixture manifest must declare release_ready=true")
        if ledgers or voices:
            _fail("pending fixture manifest must not expose unfrozen media")
        if not str(manifest.get("blocked_reason", "")).strip():
            _fail("pending fixture manifest requires a blocked_reason")
        return {
            "schema_version": manifest["schema_version"],
            "status": "pending",
            "release_ready": False,
            "ledgers": 0,
            "voices": 0,
            "languages_required": sorted(REQUIRED_LANGUAGES),
            "providers_allowed": sorted(ALLOWED_PROVIDERS),
        }
    if {item.get("language") for item in ledgers} != REQUIRED_LANGUAGES:
        _fail("ledger fixtures must contain exactly en-KE and sw-KE")
    if {item.get("language") for item in voices} != REQUIRED_LANGUAGES:
        _fail("voice fixtures must contain exactly en-KE and sw-KE")
    ids = [item.get("id") for item in [*ledgers, *voices]]
    if None in ids or len(ids) != len(set(ids)):
        _fail("fixture IDs must be present and unique")
    for ledger in ledgers:
        if ledger.get("source", {}).get("provider") not in provider_policy["allowed"]:
            _fail(f"{ledger.get('id', 'ledger')} provider is absent from the manifest allowlist")
        _validate_ledger(ledger)
    for voice in voices:
        if voice.get("source", {}).get("provider") not in provider_policy["allowed"]:
            _fail(f"{voice.get('id', 'voice')} provider is absent from the manifest allowlist")
        _validate_voice(voice)
    return {
        "schema_version": manifest["schema_version"],
        "ledgers": len(ledgers),
        "voices": len(voices),
        "languages": sorted(REQUIRED_LANGUAGES),
        "providers": sorted({item["source"]["provider"] for item in [*ledgers, *voices]}),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", type=Path, default=MANIFEST_PATH)
    parser.add_argument(
        "--allow-pending",
        action="store_true",
        help="validate the fail-closed Google-only policy before release media exists",
    )
    args = parser.parse_args()
    print(json.dumps(verify(args.manifest, allow_pending=args.allow_pending), indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
