"""Store: the storage seam.

Every agent tool and every FunctionNode talks to THIS interface, never to a
database driver. Locally the backend is SQLite (transparent, keyless,
test-friendly); in the cloud it is Firestore. Swapping backends is a config
change (DUKA_STORE env), not a code change - that seam is a deliberate
architecture point: the deterministic logic is portable because it never
learned SQL-isms or Firestore-isms.

All rows travel as plain dicts. Money is integer KSh. Phone numbers are the
customer primary key (2547XXXXXXXX), same as M-Pesa.
"""
from __future__ import annotations

from typing import Protocol


class Store(Protocol):
    # ---- lifecycle -------------------------------------------------------
    def init(self) -> None: ...
    def reset(self) -> None: ...

    # ---- catalog & customers --------------------------------------------
    def products(self) -> list[dict]: ...
    def upsert_products(self, products: list[dict]) -> None: ...
    def customers(self) -> list[dict]: ...
    def get_customer(self, customer_id: str) -> dict | None: ...
    def upsert_customers(self, customers: list[dict]) -> None: ...

    # ---- orders ----------------------------------------------------------
    def create_order(self, customer_id: str, items: list[dict], status: str,
                     needs_review: bool = False, notes: str = "",
                     created_at: str | None = None) -> int: ...
    def bulk_create_orders(self, orders: list[dict]) -> int:
        """orders: [{customer_id, items, status, total, created_at}] - the
        scale path used by the synthetic generator; one transaction."""
        ...
    def orders_for_customer(self, customer_id: str, limit: int = 5) -> list[dict]: ...
    def list_orders(self, limit: int = 100) -> list[dict]: ...
    def unpaid_orders(self) -> list[dict]: ...
    def set_order_status(self, order_id: int, status: str,
                         needs_review: bool | None = None) -> None: ...

    # ---- payments (the M-Pesa statement) ----------------------------------
    def add_payments(self, payments: list[dict]) -> int:
        """Bulk-insert statement rows; duplicate refs are dropped by the
        ledger's uniqueness constraint (deterministic dedup, no LLM).
        Returns the number of NEW rows actually inserted."""
        ...
    def unmatched_payments(self, limit: int | None = None) -> list[dict]: ...
    def link_payments(self, links: list[tuple[int, int, str]]) -> None:
        """links: [(payment_id, order_id, kind)] kind: exact|fuzzy. Bulk, one
        transaction - the exact pass settles tens of thousands of rows."""
        ...
    def payments_summary(self) -> dict: ...

    # ---- approvals (every shilling stops here) -----------------------------
    def add_approval(self, kind: str, payload: dict) -> int: ...
    def get_approval(self, approval_id: int) -> dict | None: ...
    def pending_approvals(self) -> list[dict]: ...
    def stamp_approval(self, approval_id: int, invocation_id: str,
                       payload: dict) -> None: ...
    def resolve_approval(self, approval_id: int, decision: str) -> None: ...

    # ---- cost metering -----------------------------------------------------
    def log_cost(self, row: dict) -> None: ...
    def cost_summary(self) -> dict: ...
