"""Store: the storage seam.

Every agent tool and every FunctionNode talks to THIS interface, never to a
database driver. Locally the backend is SQLite (transparent, keyless,
test-friendly); in the cloud it is Firestore. Swapping backends is a config
change (DUKA_STORE env), not a code change - that seam is a deliberate
architecture point: the deterministic logic is portable because it never
learned SQL-isms or Firestore-isms.

All rows travel as plain dicts. Money is integer KSh. Phone numbers are the
customer primary key (2547XXXXXXXX), same as M-Pesa.
"""
from __future__ import annotations

from typing import Protocol

EntityId = str | int

# A gated ledger row whose amount the model could not read may be completed by
# the owner typing it. One handwritten shop-counter line is small money, so the
# ceiling is deliberately low: a typo should bounce, not become a sale.
LEDGER_OWNER_AMOUNT_MAX = 10_000


class Store(Protocol):
    # ---- lifecycle -------------------------------------------------------
    def init(self) -> None: ...
    def reset(self) -> None: ...

    # ---- catalog & customers --------------------------------------------
    def products(self) -> list[dict]: ...
    def upsert_products(self, products: list[dict]) -> None: ...
    def customers(self) -> list[dict]: ...
    def get_customer(self, customer_id: str) -> dict | None: ...
    def upsert_customers(self, customers: list[dict]) -> None: ...

    # ---- orders ----------------------------------------------------------
    def create_order(self, customer_id: str, items: list[dict], status: str,
                     needs_review: bool = False, notes: str = "",
                     created_at: str | None = None,
                     source_event_id: str | None = None) -> EntityId: ...
    def create_owner_sale_once(self, event_id: str, customer_id: str,
                               payload_hash: str, items: list[dict],
                               status: str) -> dict: ...
    def get_order(self, order_id: EntityId) -> dict | None: ...
    def bulk_create_orders(self, orders: list[dict]) -> int:
        """orders: [{customer_id, items, status, total, created_at}] - the
        scale path used by the synthetic generator; one transaction."""
        ...
    def orders_for_customer(self, customer_id: str, limit: int = 5) -> list[dict]: ...
    def list_orders(self, limit: int = 100) -> list[dict]: ...
    def unpaid_orders(self) -> list[dict]: ...
    def set_order_status(self, order_id: EntityId, status: str,
                         needs_review: bool | None = None) -> None: ...
    # Owner decision on an order the agent proposed. Guarded and idempotent by
    # event ID: it may only move an order out of `allowed_from`, so a decision
    # can never mark money received - that stays with payment evidence.
    def decide_order_once(self, event_id: str, order_id: EntityId,
                          payload_hash: str, to_status: str,
                          allowed_from: tuple[str, ...]) -> dict: ...

    # ---- payments (the M-Pesa statement) ----------------------------------
    def add_payments(self, payments: list[dict]) -> int:
        """Bulk-insert statement rows; duplicate refs are dropped by the
        ledger's uniqueness constraint (deterministic dedup, no LLM).
        Returns the number of NEW rows actually inserted."""
        ...
    def get_payment(self, payment_id: EntityId) -> dict | None: ...
    def unmatched_payments(self, limit: int | None = None) -> list[dict]: ...
    def link_payments(self, links: list[tuple[EntityId, EntityId, str]]) -> None:
        """links: [(payment_id, order_id, kind)] kind: exact|fuzzy. Bulk, one
        transaction - the exact pass settles tens of thousands of rows."""
        ...
    def payments_summary(self) -> dict: ...

    # ---- approvals (uncertainty and irreversible effects stop here) --------
    def add_approval(self, kind: str, payload: dict) -> EntityId: ...
    def get_approval(self, approval_id: EntityId) -> dict | None: ...
    def pending_approvals(self) -> list[dict]: ...
    def stamp_approval(self, approval_id: EntityId, invocation_id: str,
                       payload: dict) -> None: ...
    def resolve_approval(self, approval_id: EntityId, decision: str) -> None: ...
    def claim_approval_decision(self, approval_id: EntityId, decision: str,
                                lease_seconds: int = 120,
                                owner_amount: int | None = None) -> dict:
        """Claim the right to apply one decision, once.

        owner_amount carries an amount the owner typed for a ledger row the
        model could not read. It is stored with the claim so the effect stays
        a pure function of the payload: replaying the same amount is
        idempotent, and a different amount conflicts like a different
        decision would.
        """
        ...
    def complete_approval_decision(self, approval_id: EntityId,
                                   decision: str) -> None: ...
    def fail_approval_decision(self, approval_id: EntityId,
                               error: str) -> None: ...
    def apply_approval_effect(self, approval_id: EntityId,
                              decision: str) -> dict: ...

    def mark_payment_kind(self, payment_id: EntityId, kind: str | None) -> None: ...

    # ---- event receipts (at-least-once delivery -> one business result) ----
    def claim_event(self, event_id: str, customer_id: str,
                    payload_hash: str, lease_seconds: int = 120) -> dict: ...
    def get_event(self, event_id: str) -> dict | None: ...
    def complete_event(self, event_id: str, result: dict) -> None: ...
    def fail_event(self, event_id: str, error: str, retryable: bool) -> None: ...

    # ---- active managed-session pointer -----------------------------------
    def get_active_session(self, customer_id: str) -> dict | None: ...
    def ensure_active_session(self, customer_id: str, user_id: str) -> dict: ...
    def rotate_active_session(self, customer_id: str, user_id: str) -> dict: ...
    def rotate_active_session_once(self, event_id: str, customer_id: str,
                                   user_id: str) -> dict: ...
    # The pointer is reserved unbound; the session service assigns the id and
    # this compare-and-set records it. Returns {"bound": bool, "pointer": dict}.
    def bind_active_session(self, customer_id: str, user_id: str, generation: int,
                            session_id: str,
                            expected_session_id: str = "") -> dict: ...

    # ---- per-customer turn serialization ---------------------------------
    def claim_customer_turn(self, customer_id: str, owner: str,
                            lease_seconds: int = 180) -> dict: ...
    def release_customer_turn(self, customer_id: str, owner: str) -> None: ...

    # ---- trusted Memory Bank outbox --------------------------------------
    def enqueue_memory_summary(self, customer_id: str, user_id: str,
                               summary: str, dedupe_key: str) -> EntityId: ...
    def claim_memory_summary(self, customer_id: str | None = None,
                             lease_seconds: int = 120) -> dict | None: ...
    def get_memory_summary(self, entry_id: EntityId) -> dict | None: ...
    def complete_memory_summary(self, entry_id: EntityId) -> None: ...
    def fail_memory_summary(self, entry_id: EntityId, error: str,
                            retryable: bool = True) -> None: ...

    # ---- messages (async channel log) ---------------------------------------
    def add_message(self, customer_id: str, direction: str, text: str,
                    channel: str = "chat", meta: dict | None = None,
                    dedupe_key: str | None = None): ...
    def messages_for(self, customer_id: str, limit: int = 50) -> list[dict]: ...

    # ---- cost metering -----------------------------------------------------
    def log_cost(self, row: dict) -> None: ...
    def cost_summary(self) -> dict: ...
